# Client Setup

FROM node:16 as build-stage

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

COPY . .

RUN ["npm", "run", "build"]

# Https setup using nginx reverse proxy

FROM nginx:1.17.0-alpine

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html 

EXPOSE $REACT_DOCKER_PORT

ENTRYPOINT ["nginx", "-g", "daemon off;"]